### ISSUE TITLE
Typo "Logging Roslyn Worksapce structure..."

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system-tools#169]
![image](https://user-images.githubusercontent.com/8040367/62174812-33fff200-b309-11e9-922f-cd5eac8a4516.png)

**Comment by jmarolf** [comment]
https://github.com/dotnet/project-system-tools/blob/9ad015d934471e4df776d78bf1e46cbb67cda4ef/src/ProjectSystemTools/RoslynLogging/RoslynLoggingResources.resx#L105

**Comment by jasonmalinowski** [comment]
@drewnoakes This can be closed?

**Comment by drewnoakes** [comment]
@jasonmalinowski yes, thanks!
