### ISSUE TITLE
Merge provider DLL into main DLL when binding problem fixed

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/project-system-tools#17]
We have to move the providers into their own DLL because Microsoft.VisualStudio.Shell.Framework.dll references Microsoft.Build.Framework.dll version 5.0 and we have to reference version 5.1 for BinaryLogger. Either the shell needs to move up to 5.1 or createpkgdef needs to add a redirect.

**Comment by drewnoakes** [comment]
These assemblies have all been merged into one.
