### ISSUE TITLE
Command handling can prevent File > Open > Folder... from working properly

### ISSUE THREAD

**Issue by vukelich** [dotnet/project-system-tools#174]
When the Project System Tools extension is installed, the `File.OpenFolder` command (File > Open > Folder...) is handled by `Microsoft.VisualStudio.ProjectSystem.Tools.BuildLogging.BuildLoggingToolWindow.InnerExec` instead of going to `Microsoft.VisualStudio.Workspace.VSIntegration.SourceExplorerPackage.Exec`. This happens when focus is on the "Build Logging" tool window. To fix this, `BuildLoggingToolWindow` needs its command handling methods (`InnerQueryStatus` and `InnerExec`) to check the value of `commandGroupGuid` in addition to `commandId`.

Repro steps:
1. Install Project System Tools version 1.0.1.1927902 to Visual Studio 2019.
1. Launch Visual Studio 2019.
1. Continue to IDE without selecting any project, solution, or folder from the Get To Code dialog.
1. Set IDE focus on the "Build Logging" tool window.
1. Use File > Open > Folder...

Expected (notice focus is in the Solution Explorer tool window)
![image](https://user-images.githubusercontent.com/3663976/65093344-d33c7f80-d971-11e9-871a-939dd8aeecd6.png)

Actual (notice focus is in the Build Logging tool window)
![image](https://user-images.githubusercontent.com/3663976/65093806-ef402100-d971-11e9-89e7-9c2a340ac379.png)

**Comment by drewnoakes** [comment]
Thanks for the great bug report. A fix has been merged and will be included in the next release.
