### ISSUE TITLE
404 error on update

### ISSUE THREAD

**Issue by EatonZ** [dotnet/project-system-tools#189]
Click "Update" and...

![404](https://user-images.githubusercontent.com/3020941/66350668-ed8ecb00-e929-11e9-80aa-d3614b0c7d71.png)

Visual Studio 2019 v16.3.2

**Comment by panopticoncentral** [comment]
This looks like it was a transient issue with the VS Marketplace, I was seeing this on other extensions as well. Are you still seeing it?

**Comment by EatonZ** [comment]
@panopticoncentral Just checked, it updated successfully this time.🙂
