### ISSUE TITLE
Cannot install on VS 2017 professional

### ISSUE THREAD

**Issue by omariom** [dotnet/project-system-tools#30]
Probably thanks to this:

https://github.com/dotnet/project-system-tools/blob/58fe80d3777261682e9597ec4aad8fb7c302c4e9/src/ProjectSystemTools/source.extension.vsixmanifest#L12

**Comment by panopticoncentral** [comment]
What version are you trying to install it into? We should install all the way up to professional, but only certain versions are supported.

**Comment by TheRubble** [comment]
Hi, Having a similar issue installing into VS2017 Enterprise.

**Comment by omariom** [comment]
@panopticoncentral 

According to the docs:

> Lists the InstallationTarget elements that describe how the package can be installed and into which Visual Studio products this extension can be installed. **Each product is identified separately by name and a version or version range.** Products can be added to the list, modified, and deleted.

**Comment by panopticoncentral** [comment]
I just pushed an update that should hopefully fix this, let me know if it's still having problems once you update.
