### ISSUE TITLE
Instructions out of date.

### ISSUE THREAD

**Issue by kaby76** [dotnet/project-system-tools#322]
I am hoping to use this extension to debug the msbuild rules (using dotnet) for my own extension. Unfortunately project-system-tools does not work.
1) I create from scratch using VS2019 16.6.2 a Net Core console app 3.1.301. It opens the project and I can build it fine.
2) After opening and "rebuild" within VS2019, I open "View => Other Windows => Build Logging" and "View => Other Windows => Build Log Message List". According to https://github.com/dotnet/project-system-tools/blob/master/img/view-menu.png, there should be a "Build Log Explorer". While the other two windows appear, "Build Log Explorer" does not appear in the UI, anywhere.
3) After doing Build, Rebuild, and Clean, I would expect to see something in one of these windows for something. There is absolutely nothing.

**Comment by kaby76** [comment]
"_dataSource.IsLogging" was always false. It turns out I never pressed the "Start" icon. I see normal builds, but not any design-time builds.

**Comment by drewnoakes** [comment]
Design time builds occur only when a project is changed in some way.

I am not sure there's anything actionable here so will close this out. Let me know if I missed something.
