### ISSUE TITLE
Make sure that updating VS past 2019 will not break GetLogForBuildAsync

### ISSUE THREAD

**Issue by ericdyoon** [dotnet/project-system-tools#356]
GetLogForBuildAsync
- Currently uses an interface on: VisualStudioServices.VS2019_6.FileSystem
- using this interface could break once VS updates beyond 2019, mainly transferring binlogs from the filesystem on the server to the client's machine.

Edit:
- becoming outdated should not cause code to break, but there are also more up to date services available.

**Comment by dmonroym** [comment]
It shouldn't break anything but there are later versions available, would it make sense to use the latest?
https://devdiv.visualstudio.com/DevDiv/_git/VS.RPC.Contracts?path=%2Fsrc%2FMicrosoft.VisualStudio.RpcContracts%2FVisualStudioServices%2BVS2019_8.cs
