### ISSUE TITLE
After installing Extension loading a solution causes error.

### ISSUE THREAD

**Issue by TerryWickens** [dotnet/project-system-tools#36]
![image](https://user-images.githubusercontent.com/22141274/33585733-791bb1d6-d9b1-11e7-8eb2-58d9a00bffcf.png)

**Comment by TerryWickens** [comment]
Can load solution after message but will not build.

**Comment by CNBoland** [comment]
I'm experiencing this, too. From attached ActivityLog.xml:

"System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."

[ActivityLog.xml.txt](https://github.com/dotnet/project-system-tools/files/1532231/ActivityLog.xml.txt)

**Comment by CNBoland** [comment]
I found a partial workaround. The error dialog no longer pops up when loading a solution, but no output appears in the Build Logging window, even when building the entire solution.

Download the System.ValueTuple package from [here:](https://www.nuget.org/packages/System.ValueTuple/). I used version 4.4. Open the file in a .zip archive tool or change file extension to .zip and open in Windows Explorer.

Extract \lib\net461\System.ValueTuple.dll and copy to folder C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\Project. Note that 'Enterprise' is the edition of Visual Studio, so yours may be not be Enterprise.

**Comment by panopticoncentral** [comment]
Are people seeing this installing on an install of Visual Studio 15.5?

**Comment by CNBoland** [comment]
@panopticoncentral , I meant to come back with versions. I have:
- Project System Tools 1.0.0.6232701
- Visual Studio Enterprise 2017 15.4.5

**Comment by BrightLight** [comment]
@panopticoncentral I was on VS Enterprise 2017 15.3.5, VSIX denied installation. So I updated to 15.5.0. When I try to open the "Build Logging" window before I open any solution I get "Exception has been thrown by the target of an invocation". When I try to open a solution I get the same error as reported by @TerryWickens.

**Comment by OsirisTerje** [comment]
@panopticoncentral  Updated to 15.5 today, and then it appeared.  No issue with 15.4 latest.  
Activitylog.xml shows a few errors, like this one:
![image](https://user-images.githubusercontent.com/203432/33654810-9193f0e6-da71-11e7-8017-1c78a7aed46d.png)

Attached the complete activitylog
[ActivityLog.zip](https://github.com/dotnet/project-system-tools/files/1534589/ActivityLog.zip)

**Comment by Reonekot** [comment]
Another me2 - I got the error after updating from 15.4.5 to 15.5, so I have disabled to tool for now in 15.5.

**Comment by willockss** [comment]
Visual Studio Professional - 15.5.0 
Updated extension today and the same errors as above.
Disabled extension and VS s not complaining anymore

**Comment by jberke** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.4.0
VisualStudio.15.Release/15.4.0+27004.2002
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Enterprise

**Comment by Pilchie** [comment]
Tagging @terrajobst @AlexGhiondea @jaredpar - this is a project targeting .NET 4.6 and referencing System.ValueTuple 4.4.  Any idea why ValueTuple wouldn't be found?  Other parts of VS use it fine...

**Comment by panopticoncentral** [comment]
I just pushed a new version of the extension without the ValueTuple reference, hopefully this should fix it.
