### ISSUE TITLE
#nullable disable currently used in project-system to handle code analysis

### ISSUE THREAD

**Issue by tMOEqJOE** [dotnet/project-system-tools#369]
On files from project-system-tools, nullable types are not being used currently, so #nullable disable is being used to suppress build warnings.

goal of this issue is to remove the #nullable disable lines and then use nullable types in the files that are missing them.

**Comment by drewnoakes** [comment]
This was addressed in d2ab9387ea8593ae08ed90b4545b18f253f778d5.
