### ISSUE TITLE
Build project-system-tools for Dev17 / VS2022

### ISSUE THREAD

**Issue by edwardskrod** [dotnet/project-system-tools#398]
Project System Tools is currently not installable on dev17.  

![PST](https://user-images.githubusercontent.com/5585130/121951326-cb696500-cd28-11eb-8a23-77bdd6bb4b78.png)

**Comment by dmonroym** [comment]
@edwardskrod we've fixed this in #392 but are working on a release plan as this update wouldn't work on dev16. If you'd like to use it you can try compiling from that branch or reach out to myself or @drewnoakes and we can provide a temporary build

**Comment by edwardskrod** [comment]
@dmonroym  Thanks Daniel!  I reached out to Drew.
