### ISSUE TITLE
U2DCheckVerbosity

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system-tools#40]
Do we have a replacement for U2DCheckVerbosity? Does it print for each project why it chose to rebuild it?

There are some instructions here on how to set U2DCheckVerbosity in VS 2017:
https://developercommunity.visualstudio.com/content/problem/161997/full-build-every-time-with-155.html

If they are still relevant, we should perhaps document them at 
https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#diagnosing-design-time-builds

**Comment by panopticoncentral** [comment]
There are options in VS for the .NET Core/.NET Framework to turn on logging for the up to date check. For .NET Framework projects, U2DCheckVerbosity is still the only way to do it and it's not official supported. It's not technically related to design-time builds, but if you want to open an issue in the project system repo, we can look at adding some docs there...

**Comment by aolszowka** [comment]
I am sorry to resurrect an old thread, but we were recently on a call discussion performance and this particular registry key came up in talking with Cyrus Najmabadi; was there ever an issue opened in the Project System Repo for this?

**Comment by KirillOsenkov** [comment]
As far as I know it was decided to not fix this in the old project system. The new CPS-based project system should give good diagnostics.

**Comment by KirillOsenkov** [comment]
See https://github.com/dotnet/project-system/issues/2412 for details. @jjmew
