### ISSUE TITLE
git clean

### ISSUE THREAD

**Issue by johnkors** [dotnet/project-system-tools#45]
Hi, sorry if I'm in the wrong place - please redirect me to where to provide this if not here.

If you do a git clean having Visual Studio 2017 with a solution open, it's keeping a lot of locks on files. Any way around this other than closing Visual Studio for each clean?

```
λ git clean -xfd
Unlink of file 'source/.vs/MySampleProject/v15/Server/sqlite3/db.lock' failed. Should I try again? (y/n) n
Unlink of file 'source/.vs/MySampleProject/v15/Server/sqlite3/storage.ide' failed. Should I try again? (y/n) n
Unlink of file 'source/.vs/MySampleProject/v15/Server/sqlite3/storage.ide-shm' failed. Should I try again? (y/n) n
Unlink of file 'source/.vs/MySampleProject/v15/Server/sqlite3/storage.ide-wal' failed. Should I try again? (y/n) n
```

**Comment by drewnoakes** [comment]
@johnkors this repository is for a VS extension that shows information about builds.

Your issue is more related to core VS functionality and should be directed to Connect. The easiest way to do that is to use the Feedback feature in VS itself.
