### ISSUE TITLE
support properties for Central Package Management (CPM) missing

### ISSUE THREAD

**Issue by Bertk** [dotnet/project-system-tools#477]
Project System Tools 2022 1.0.2.2305901 does not support [Central Package Management (CPM)](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management) and creates message "**Possible unused or misspelled property**".

<img width="631" alt="image" src="https://github.com/dotnet/project-system-tools/assets/2315215/2eefc586-739b-4a27-99c2-df3778cc739c">

**Comment by drewnoakes** [comment]
I believe your screenshot is showing diagnostics from https://github.com/mhutch/MonoDevelop.MSBuildEditor, not from Project System Tools.

**Comment by Bertk** [comment]
Sorry, but I noticed this only after installing the Project System Tools 2022 tools.

**Comment by drewnoakes** [comment]
No problem. It happens.
