### ISSUE TITLE
Suggest user install the MSBuild Structured Log Viewer

### ISSUE THREAD

**Issue by tmeschter** [dotnet/project-system-tools#5]
Idea:

When the Build Logging window opens we check the file associations to see if anything is installed that knows how to handle .binlog files. If there is, we pop up an Info Bar suggesting they go to http://msbuildlog.com/ and install the MSBuild Structured Log Viewer. I believe its installer sets up the appropriate file association.

The Info Bar should include a "Don't show me this again" option so we don't keep nagging users who don't install the Viewer.

**Comment by panopticoncentral** [comment]
We're working on integrating this directly into the tools.
