### ISSUE TITLE
How to get more verbose logs

### ISSUE THREAD

**Issue by grokys** [dotnet/project-system-tools#53]
When using the extension to capture build logs to diagnose https://github.com/dotnet/sdk/issues/2535 in https://github.com/github/VisualStudio, my build logs are not reporting anything useful:

![image](https://user-images.githubusercontent.com/1775141/45616325-6301d200-ba6f-11e8-9327-7b4f57af0b59.png)

I've set "Detailed" log file verbosity:

![image](https://user-images.githubusercontent.com/1775141/45616347-77de6580-ba6f-11e8-91f4-102f0beee64f.png)

But it seems to have made no difference. Looking at the same project build from the command line on the other hand gives a far more detailed picture of what's going on:

![image](https://user-images.githubusercontent.com/1775141/45616408-ae1be500-ba6f-11e8-9f4f-ba0fff0f077f.png)

How do I get the same level of detail from a VS build?

**Comment by jmarolf** [comment]
Set the log level to diagnostic
![image](https://user-images.githubusercontent.com/9797472/45634044-4311e480-ba56-11e8-80d1-2bcee099b1c1.png)

**Comment by grokys** [comment]
Sorry, I probably should have mentioned that I tried that and the output is the same.

**Comment by jmarolf** [comment]
So this is happening in an "design-time build" which is not the same thing as a regular build.  In this case a different set of targets is run from the commandline build.  You should be seeing different outputs.

**Comment by grokys** [comment]
Actually looking at the output again: this isn't a DesignTime build:

![image](https://user-images.githubusercontent.com/1775141/45682002-5187fb00-bb3f-11e8-8304-8d947d776aa4.png)

**Comment by panopticoncentral** [comment]
I think this is the same issue as #34,

**Comment by panopticoncentral** [comment]
Or maybe #59.
