### ISSUE TITLE
Only evaluation shown for csproj projects

### ISSUE THREAD

**Issue by kzu** [dotnet/project-system-tools#54]
This is the result of a full solution build (after doing FIle | New | Cross-Platform | Mobile App (Xamarin), so, no previous build). It can also be reproduced with a .NET desktop console app:

![image](https://user-images.githubusercontent.com/169707/48722063-f25b6b00-ec01-11e8-9f88-8f5d076d6549.png)

```
Microsoft Visual Studio Enterprise 2017 
Version 15.9.1
VisualStudio.15.Release/15.9.1+28307.105
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.
```

This seems to have become broken sometime between 15.8 and 15.9.
DTB is also showing only for the CPS project.

**Comment by kzu** [comment]
@Pilchie the thing I mentioned, that's making harder for Xamarin users to report binary logs to us :(

**Comment by panopticoncentral** [comment]
@kzu, are you still seeing this? I tried a .NET desktop console app with the latest preview and it looks to be OK so maybe this was an issue that got fixed? If you are still having problems with Xamarin, please reactivate and I'll take a look.
