### ISSUE TITLE
Evaluation events are dropped by MuxLogger

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/project-system-tools#59]
It looks like MuxLogger is dropping all Evaluation events here:
https://source.dot.net/#Microsoft.Build.Utilities.Core/MuxLogger.cs,619

If a message doesn't belong to the submission it is dropped.

All evaluation events have an invalid submission ID (-1):
https://source.dot.net/#Microsoft.Build/Definition/Project.cs,2725

Not sure what to do here - either associate evaluation events with a submission or fix the mux logger to accept evaluation events? Or perhaps not use MuxLogger in `C:\ProjectServices\src\Microsoft.VisualStudio.ProjectServices\DesignTimeBuild\DesignTimeBuildScheduler.cs`?

**Comment by KirillOsenkov** [comment]
@panopticoncentral I think I've found where logging is trimmed for design-time builds: the MuxLogger in DesignTimeBuildScheduler.cs.

**Comment by KirillOsenkov** [comment]
Looks like it's probably not an issues with Project System Tools, or CPS, or ProjectServices. I think it's an actual MSBuild bug, see the details here:
https://github.com/Microsoft/msbuild/issues/4044

**Comment by panopticoncentral** [comment]
You fixed this @KirillOsenkov, correct?

**Comment by KirillOsenkov** [comment]
Yes, this is now fixed, thanks.
