### ISSUE TITLE
Restore the ability to open log files directly with Structured Log Viewer

### ISSUE THREAD

**Issue by bording** [dotnet/project-system-tools#64]
While I understand the goals of making the extension self-contained, the changes in the latest release have made things much less useful.

Previously, Open Logs would open the log file directly in Structured Log Viewer (and the repo README still documents that it does this). Now, it opens in a view directly in VS.

I would very much like to have the the ability back to open log files directly into Structured Log Viewer without first having to save the file.

Structured Log Viewer is a a much more useful tool to use to analyze log files at this point, and having to first save the file before I can open it is a big speed bump in my workflow.

**Comment by ltrzesniewski** [comment]
Same here, I'd like the logs to open in the log viewer on double-click.

FWIW here's my current workaround: open the log, then right click on the editor tab and choose "Open Containing Folder", then double-click on the file. That's not ideal, but still faster than saving the file.

**Comment by ltrzesniewski** [comment]
Ok, actually there's a solution: find a .binlog file in the solution explorer, then right click and choose "Open With...".

Here you can set the MSBuild structured log viewer as default:

![image](https://user-images.githubusercontent.com/7913492/52779467-85147600-3048-11e9-8f65-5fe40474a93f.png)

**Comment by honzajscz** [comment]
@[ltrzesniewski](/ltrzesniewski) Thanks for your advice!

**Comment by bording** [comment]
I've tried the workaround @ltrzesniewski suggested, and it's working, but I'm also getting an error. 

The first time I try to double click on entry the file opens, but I also get:

![image](https://user-images.githubusercontent.com/753669/53610745-fb14f300-3b99-11e9-871a-efbdc83be410.png)

And the error in the referenced file is:
```
  <entry>
    <record>3477</record>
    <time>2019/03/01 01:36:27.535</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.ProjectSystem.Tools.BuildLogging.BuildLoggingToolWindow.OpenLog(ITableEntryHandle tableEntry)&#x000D;&#x000A;   at Microsoft.VisualStudio.ProjectSystem.Tools.BuildLogging.UI.BuildLogTableEventProcessor.PostprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass40_0.&lt;OnEntryElementNavigate&gt;b__4(ITableControlEventProcessor p, ITableEntryHandle entry)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass60_2`1.&lt;EventProcessorHandler&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

After the first time, all double clicks open the file without the error. However, every time I right click and use Open Logs, the file opens and I get:

![image](https://user-images.githubusercontent.com/753669/53610836-6959b580-3b9a-11e9-95d7-f4acf13971b5.png)


This is on VS 2019 RC BTW.

**Comment by bording** [comment]
@panopticoncentral Any thoughts on this?

**Comment by panopticoncentral** [comment]
It's reasonable. Probably the short term fix is to add a menu item to open in the structured log viewer and maybe longer term to add an option that would allow people to set a double-click default.

**Comment by panopticoncentral** [comment]
OK, the PR is now published to the marketplace. Not sure how long it will take to propagate.

**Comment by bording** [comment]
@panopticoncentral I see the update already, thanks!

I do wonder if this issue should stay open, however, since there's no way in the extension itself to set how to open the log files. It's only through a rather [non-discoverable workaround](https://github.com/dotnet/project-system-tools/issues/64#issuecomment-463569397) that you can restore the previous behavior.

**Comment by natemcmaster** [comment]
I agree with @bording. I'd prefer to use Kirill's log viewer instead, and had to find this issue to figure out how to workaround this one.

**Comment by panopticoncentral** [comment]
I just pushed an update that adds an "Open Log External" menu item that will open in the external viewer. Let me know how that works!

**Comment by bording** [comment]
I just updated and the new option does seem to work fine. For people new to the extension, it does provide a discoverable way to use an external viewer.

Overall, I still prefer the previous behavior of having a double click open the log in the external viewer by default, but I can live with needing to manually change the default program as described in https://github.com/dotnet/project-system-tools/issues/64#issuecomment-463569397 to restore that behavior.

**Comment by kzu** [comment]
I'd close this issue, since the Open Log External (context menu) command is pretty much all I need.
