### ISSUE TITLE
NullReferenceException in VS 2019

### ISSUE THREAD

**Issue by daveaglick** [dotnet/project-system-tools#66]
I'm experiencing NREs in VS 2019 as reported in a comment here: https://github.com/dotnet/project-system-tools/issues/64#issuecomment-468510800 - my experiences are exactly the same as described in that comment.

I get this message on the first attempt:
![2019-04-05_13h13_05](https://user-images.githubusercontent.com/1020407/55645010-75422400-57a5-11e9-858c-3d1cfbc1e3e0.png)

And then this dialog on following attempts:
![2019-04-05_13h20_04](https://user-images.githubusercontent.com/1020407/55645088-999e0080-57a5-11e9-8a67-7e5473483d9d.png)

**Comment by bording** [comment]
I've opened a PR to fix the problem: #67
